############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About Us"
url = "about/"
weight = 2

[[main]]
name = "Our Services"
url = "services/"
weight = 3
hasChildren = true

[[main]]
parent = "Our Services"
name = "Infrastructure Design"
url = "services/infrastructure-design/"

[[main]]
parent = "Our Services"
name = "Infrastructure as a Code"
url = "services/iac/"

[[main]]
parent = "Our Services"
name = "Kubernetes Managed Services"
url = "services/managed-k8s/"

[[main]]
parent = "Our Services"
name = "Container Solutions"
url = "services/container-solutions/"

[[main]]
parent = "Our Services"
name = "CI/CD Pipelines"
url = "services/cicd-pipelines/"

[[main]]
parent = "Our Services"
name = "Monitoring and Logs Management"
url = "services/monitoring-and-logs/"

[[main]]
name = "Case Studies"
url = "case-studies/"
weight = 4
hasChildren = true

[[main]]
parent = "Case Studies"
name = "AWS OpsWorks to AWS Fargate Migration"
url = "case-studies/opsworks-to-fargate/"

[[main]]
parent = "Case Studies"
name = "Transition from Terraform + Ansible to Kubernetes"
url = "case-studies/terraform-asible-to-kubernetes/"

[[main]]
parent = "Case Studies"
name = "AWS ECS to AWS EKS migration"
url = "case-studies/ecs-to-eks/"

[[main]]
name = "Blog"
url = "blog/"
weight = 5


# footer menu
[[footer]]
name = "About Us"
url = "about/"
weight = 1

[[footer]]
name = "Our Services"
url = "services/"
weight = 2

[[footer]]
name = "Case Studies"
url = "case-studies/"
weight = 3

[[footer]]
name = "Contact"
url = "contact/"
weight = 4