######################## default configuration ####################
baseURL = "/"
title = "Cloud Native Solutions"
theme = "cns-modern"
timeZone = "Europe/Bucharest"
paginate = 10
summaryLength = 20
hasCJKLanguage = false

########################### Services #############################
[services]
[services.googleAnalytics]
ID = 'G-8XEPD0RKMQ'

############################# Outputs ############################
[outputs]
home = ["HTML", "RSS"]

############################# Imaging ############################
[imaging]
quality = 90
resampleFilter = "Lanczos"

############################ Markup ##############################
[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'monokai'

[markup.tableOfContents]
startLevel = 2
endLevel = 5
ordered = true

############################# Params ##############################
[params]
description = "Your On-Demand Cloud Native Experts — DevOps-as-a-Service, Kubernetes, CI/CD, IaC, Cloud Infrastructure"
