name = "Cloud Native Solutions"
license = "MIT"
licenselink = "https://github.com/CloudNative-Solutions/CloudNative-Solutions.github.io/blob/main/LICENSE"
description = "Cloud Native Solutions Theme"
homepage = "https://github.com/CloudNative-Solutions/CloudNative-Solutions.github.io"
demosite = "https://CloudNative-Solutions.github.io"
min_version = "0.121.2"

tags = [
  "blog",
  "responsive",
  "minimal",
  "personal",
  "light",
  "dark",
  "multilingual",
  "landing",
  "contact",
  "dark mode",
  "tailwindcss",
]

features = [
  "Multi-Authors",
  "Search",
  "Multilingual",
  "Dark Mode",
  "Taxonomies",
]

[author]
name = "Marius Oprin"
homepage = "https://marius.oprin.ro"

[original]
author = "Marius Oprin"
homepage = "https://marius.oprin.ro"
repo = "https://github.com/CloudNative-Solutions/CloudNative-Solutions.github.io"
